// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo5kCK90yY24GmIywzMZOU7r2MkA_g6c4',
    appId: '1:1060417419957:web:4d00c4c9112da7a2ae1cfc',
    messagingSenderId: '1060417419957',
    projectId: 'cwdapp-91162',
    authDomain: 'cwdapp-91162.firebaseapp.com',
    storageBucket: 'cwdapp-91162.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY-G5vpDjdR92HP5eAQjRA3YAerUlp8pE',
    appId: '1:1060417419957:android:6e8bb8c16b96ea5dae1cfc',
    messagingSenderId: '1060417419957',
    projectId: 'cwdapp-91162',
    storageBucket: 'cwdapp-91162.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC12FkPXgXrWdIN_zf7vy7gIV2b6Jc8prI',
    appId: '1:1060417419957:ios:8880b5ee5e2f5014ae1cfc',
    messagingSenderId: '1060417419957',
    projectId: 'cwdapp-91162',
    storageBucket: 'cwdapp-91162.appspot.com',
    iosBundleId: 'com.example.cwdapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC12FkPXgXrWdIN_zf7vy7gIV2b6Jc8prI',
    appId: '1:1060417419957:ios:7da93eef46d88663ae1cfc',
    messagingSenderId: '1060417419957',
    projectId: 'cwdapp-91162',
    storageBucket: 'cwdapp-91162.appspot.com',
    iosBundleId: 'com.example.cwdapp.RunnerTests',
  );
}
